### PR TITLE
Update React to 18.0 and regenerate package-lock

### PR DESCRIPTION
**Pull request by aiddun**
This package's current React version in package.json is set to 16, which leads npm to error with the current react version. Tests pass, feel free to verify.

### CODE REVIEW

**Comment by jango707** [comment]
Any updates on merging this PR? 🥺

**Comment by kian1991** [comment]
yeah i also would second this...messes with my project

**Comment by shibli21** [comment]
can this pr be merged ?

**Comment by aiddun** [comment]
@xurban42

**Comment by Oxymoron290** [comment]
@aiddun can you resolve the merge conflict please?

**Comment by aiddun** [comment]
@Oxymoron290 I will if any of the maintainers say that they'll actually merge the changes

**Comment by aiddun** [comment]
Otherwise I think you can set my fork as the source in npm, haven't tried it

**Pull request closed without merging**
