### PR TITLE
peer dependency update

### PR DESCRIPTION
**Pull request by DK013**
- peer dependency for React and React-dom updated to v18.2.0
- removed dist from .gitignore so npm can install from git
- tested with latest dependency

### CODE REVIEW

**Review by ercumentlacin — APPROVED** [review]
well done 🎊

**Review by hewseph — APPROVED** [review]
Wonderful

**Comment by fatherabraham-hms** [comment]
@ercumentlacin @hewseph - do either of you have access to merge this PR to update react-camera-pro to react v18?

**Comment by ercumentlacin** [comment]
> @ercumentlacin @hewseph - do either of you have access to merge this PR to update react-camera-pro to react v18?

I'm unfortunately not authorized to merge.

**Comment by fatherabraham-hms** [comment]
@xurban42 @ptomasko @ScreamZ @atb-anson - this PR to upgrade react-camera-pro to v18 would be super helpful to have in the public repo - are you able to merge possibly?

**Pull request merged**
